/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define if you don't have vprintf but do have _doprnt.  */
/* #undef HAVE_DOPRNT */

/* Define if you have the vprintf function.  */
/* #undef HAVE_VPRINTF */

/* Define as __inline if that's what the C compiler calls it.  */
#define inline __inline__

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have the err function.  */
#define HAVE_ERR 1

/* Define if you have the strerror function.  */
/* #undef HAVE_STRERROR */

/* Define if you have the xmalloc function.  */
/* #undef HAVE_XMALLOC */

/* Define if you have the xrealloc function.  */
/* #undef HAVE_XREALLOC */

/* #undef HAVE_XCALLOC */

/* Define if you have the xstrdup function.  */
/* #undef HAVE_XSTRDUP */

#define HAVE_HEAPSORT 1

#include <stddef.h>


extern int heapsort (void *, size_t, size_t, int (*) (const void *, const void *));
extern int write_m(int);
